### ISSUE TITLE
[Bug]Settling Probe and Klipper 13 Error

### ISSUE THREAD

**Issue by Cyondil** [voidtrance/voron-klipper-extensions#17]
**Describe the bug**
After upgrading to Klipper 13, I started getting an error that stated.
Internal error during connect: ProbeSessionHelper.__init__() missing 1 required positional argument: 'start_session_cb'

Based on my klippy.log, this is where the specific error occurs:
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 130, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 123, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 112, in load_object
    self.objects[section] = init_func(config.getsection(section))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/klipper/klippy/extras/settling_probe.py", line 125, in load_config
    return SettlingProbe(config)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/klipper/klippy/extras/settling_probe.py", line 110, in __init__
    self.probe_session = SettlingProbeSessionHelper(probe_config, config, self.mcu_probe)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/klipper/klippy/extras/settling_probe.py", line 55, in __init__
    ProbeSessionHelper.__init__(self, probe_config, mcu_probe)
TypeError: ProbeSessionHelper.__init__() missing 1 required positional argument: 'start_session_cb'

**To Reproduce**
1. Enable the Settling Probe section in printer.cfg
2. Restart Klipper
3. Error shows up
4. Disabling Settling Probe section in printer.cfg makes the issue go away
7. See error**Expected behavior** Klipper successfully start and settling probe working on probing. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/bc74525d-e52d-4f9c-857c-52e4d104b2d2)

![Image](https://github.com/user-attachments/assets/cf230ac0-ccf4-464f-bc37-84dad0ee7a62)

**Repository Verions**
Please, provide the head commit of the following repositories:
- Klipper
1f5783a25056669a3d158fa0cf05271ef7f3a3fc (HEAD -> master, origin/master, origin/HEAD) probe: Remove ProbeEndstopSessionHelper

- voron-klipper-extensions
"8f35661aa589b891ae92dcaee3bfa62bddbb5763 (HEAD -> master, origin/master, origin/HEAD) [state_notify] Fix printer "printing" detection
(added quote at the beginning to prevent autoformatting issue with the number sequence)

- Moonraker
7cdcca3cb4b7caf27d511d1c4e32fa3297391709 (HEAD -> master, origin/master, origin/HEAD) build: bump pillow for Python >=3.9

**Logfiles**

[klippy.log](https://github.com/user-attachments/files/19816616/klippy.log)

**Additional context**
N/A

**Comment by strayr** [comment]
Getting exactly the same after upgrade to v0.13.0-50-gf2b27d17b, this is my only upgrade blocker.

**Comment by CBoismenu** [comment]
Just updated voron-klipper-extensions to the latest version v0.0.1-60-gd7792457 and klipper to version v0.13.0-51-gbfda326c.

Although printer boots fine but as soon as settling_probe is used I get a firmware error.

Internal error on command:"QUAD_GANTRY_LEVEL"

Even if I set settling_sample to false I get the error.

If I totally disable settling_probe, # tags in front of every line, it works as expected.

**Comment by voidtrance** [comment]
Commit c5db0e9 should be taking care of the issue described in the original report.

@CBoismenu, please update to the latest just to make sure that you have the commit in question. If you are still having issues, please open a new issue.
